### ISSUE TITLE
Slider does only work oneway

### ISSUE THREAD

**Issue by klaus31** [Bjornnyborg/vue-custom-range-slider#2]
When the `v-model` changes its value, the slider does not jump to the right position.

E.g. when I put this button to the ["Usage with custom values"-Example](https://github.com/Bjornnyborg/vue-custom-range-slider#usage-with-custom-values) `<button @click="slider = 'd'">Set 'd'</button>`, then `{{slider}}` shows the right number, but the position of the slider is still at position "a".

Using vue 2.6.11

**Comment by Bjornnyborg** [comment]
Hello @klaus31 , sorry for the long response time!
Please upgrade to latest version, this should now be possible.
See example: https://codesandbox.io/embed/vue-template-forked-n3gce

Let me know if you have any problems!
