### ISSUE TITLE
Can :values be set dynamically ?

### ISSUE THREAD

**Issue by mdpradeep** [Bjornnyborg/vue-custom-range-slider#4]
As per https://github.com/Bjornnyborg/vue-custom-range-slider#usage-with-custom-values `:values` can be set to custom values. Can these values change ? I have been trying to set `sliderValues` to different values but it always has what it started with. Is having `sliderValues` set on-the-fly even possible ?

**Comment by Bjornnyborg** [comment]
Hello @mdpradeep , sorry for the long response time!
Please upgrade to latest version, this should now be possible.
See example: https://codesandbox.io/embed/vue-template-forked-n3gce

Let me know if you have any problems!
